# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'HeartRatePlotter' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HeartRatePlotter
  pod 'Charts', '~> 3.0.1'

  target 'HeartRatePlotterTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HeartRatePlotterUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
